/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlsoLikeSection: typeof import('./src/components/sections/AlsoLikeSection.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    CartContain: typeof import('./src/components/common/CartContain.vue')['default']
    CartModal: typeof import('./src/components/modals/CartModal.vue')['default']
    CategoriesSection: typeof import('./src/components/sections/CategoriesSection.vue')['default']
    CategoryCard: typeof import('./src/components/sections/CategoryCard.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    HomeProductsSection: typeof import('./src/components/sections/HomeProductsSection.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InvitationSection: typeof import('./src/components/sections/InvitationSection.vue')['default']
    MenuBar: typeof import('./src/components/navigation/MenuBar.vue')['default']
    Message: typeof import('primevue/message')['default']
    OrderedModal: typeof import('./src/components/modals/OrderedModal.vue')['default']
    ProductFullSection: typeof import('./src/components/sections/ProductFullSection.vue')['default']
    ProductPreviewSection: typeof import('./src/components/sections/ProductPreviewSection.vue')['default']
    QuantityInput: typeof import('./src/components/common/QuantityInput.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
