/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxGroup: typeof import('primevue/checkboxgroup')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormNav: typeof import('./src/components/FormNav.vue')['default']
    FormStep1: typeof import('./src/components/FormStep1.vue')['default']
    FormStep2: typeof import('./src/components/FormStep2.vue')['default']
    FormStep3: typeof import('./src/components/FormStep3.vue')['default']
    FormStep4: typeof import('./src/components/FormStep4.vue')['default']
    FormThank: typeof import('./src/components/FormThank.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
